import type { SceneDefinition } from "./types";

export function buildDemoSceneDefinition(
  sceneCode = `demo_scene_${Date.now()}`,
): SceneDefinition {
  return {
    sceneCode,
    sceneName: "电商下单核心链路 (演示)",
    sceneType: "ecommerce",
    sceneRemark:
      "演示场景：HTTP 用户登录获取 Token → SQL 查询库存 → HTTP 创建订单 → SQL 记录订单日志，展示请求映射、响应提取与参数传递。",
    environmentField: "env",
    status: "DRAFT",
    inputSchema: [
      {
        name: "env",
        label: "环境标识",
        remark: "用于切换测试/预发/生产环境",
        type: "string",
        required: true,
        batchEnabled: false,
      },
      {
        name: "userId",
        label: "用户ID",
        remark: "下单买家唯一标识",
        type: "string",
        required: true,
        batchEnabled: true,
        defaultValue: "U8899",
      },
      {
        name: "productId",
        label: "商品编号",
        remark: "待购买商品SKU编号",
        type: "string",
        required: true,
        batchEnabled: true,
        defaultValue: "P1024",
      },
      {
        name: "buyCount",
        label: "购买数量",
        remark: "单次购买件数",
        type: "number",
        required: false,
        batchEnabled: true,
        defaultValue: 2,
      },
    ],
    steps: [
      {
        stepId: "user_login",
        stepName: "1. 用户登录获取Token",
        type: "HTTP",
        enabled: true,
        dependsOn: [],
        description: "调用认证服务登录接口，获取访问令牌供后续步骤使用",
        sysCode: "auth",
        method: "POST",
        path: "/api/v1/login",
        timeoutConfig: {
          connectTimeoutSeconds: 10,
          readTimeoutSeconds: 10,
          writeTimeoutSeconds: 10,
          poolTimeoutSeconds: 10,
        },
        requestMapping: {
          headers: { "Content-Type": "application/json" },
          body: { userId: "${input.userId}", grantType: "password" },
        },
        bodySchema: [
          {
            name: "userId",
            label: "用户ID",
            remark: "登录账号标识",
            type: "string",
            required: true,
            batchEnabled: false,
          },
          {
            name: "grantType",
            label: "授权类型",
            remark: "OAuth2授权模式",
            type: "string",
            required: false,
            batchEnabled: false,
          },
        ],
        responseSchema: [
          {
            name: "code",
            label: "响应码",
            remark: "业务状态码，200为成功",
            type: "string",
            required: false,
            batchEnabled: false,
            defaultValue: "200",
          },
          {
            name: "message",
            label: "响应消息",
            remark: "服务端返回的描述信息",
            type: "string",
            required: false,
            batchEnabled: false,
            defaultValue: "success",
          },
          {
            name: "data",
            label: "响应数据",
            remark: "业务数据载体",
            type: "object",
            required: false,
            batchEnabled: false,
            children: [
              {
                name: "accessToken",
                label: "访问令牌",
                remark: "JWT格式Token，有效期2小时",
                type: "string",
                required: false,
                batchEnabled: false,
                defaultValue: "eyJhbGciOiJIUzI1NiJ9...",
              },
              {
                name: "expiresIn",
                label: "过期时间",
                remark: "Token有效时长(秒)",
                type: "number",
                required: false,
                batchEnabled: false,
                defaultValue: 7200,
              },
            ],
          },
        ],
        responseHandling: {
          expectedContentType: "JSON",
          statusCode: { success: [200] },
          businessSuccess: {
            allOf: [{ path: "${RES_BODY(code)}", op: "EQ", value: "200" }],
          },
          businessFailure: { anyOf: [] },
        },
        outputMapping: {
          accessToken: "${RES_BODY(data.accessToken)}",
          expiresIn: "${RES_BODY(data.expiresIn)}",
        },
        outputMeta: {
          accessToken: {
            label: "访问令牌",
            remark: "JWT格式，后续请求携带此Token鉴权",
          },
          expiresIn: { label: "过期时间", remark: "单位秒，默认7200" },
        },
        httpParamMapping: {},
      },
      {
        stepId: "check_inventory",
        stepName: "2. 查询商品库存",
        type: "SQL",
        enabled: true,
        dependsOn: ["user_login"],
        description: "查询商品库存表，确认商品可用且库存充足",
        operation: "SELECT",
        sysCode: "trade",
        datasourceCode: "tradeDb",
        sqlText:
          "SELECT stock_num, status FROM product_inventory WHERE product_id = :productId",
        normalizedSql:
          "SELECT stock_num, status FROM product_inventory WHERE product_id = :productId",
        paramMapping: {
          productId: "${input.productId}",
        },
        outputMapping: {
          stock_num: "stock_num",
          product_status: "status",
        },
        outputMeta: {
          stock_num: { label: "库存数量", remark: "当前可售库存数" },
          product_status: {
            label: "商品状态",
            remark: "ON_SALE=在售, OFF_SHELF=已下架",
          },
        },
      },
      {
        stepId: "create_order",
        stepName: "3. 创建交易订单",
        type: "HTTP",
        enabled: true,
        dependsOn: ["user_login", "check_inventory"],
        description: "携带登录Token调用交易中台创建订单",
        sysCode: "trade",
        method: "POST",
        path: "/api/v2/orders/create",
        timeoutConfig: {
          connectTimeoutSeconds: 10,
          readTimeoutSeconds: 10,
          writeTimeoutSeconds: 10,
          poolTimeoutSeconds: 10,
        },
        requestMapping: {
          headers: {
            "Content-Type": "application/json",
            Authorization: "Bearer ${steps.user_login.outputs.accessToken}",
          },
          body: {
            requestNo: "${system.uuid}",
            timestamp: "${system.now}",
            buyer: { id: "${input.userId}" },
            items: [
              {
                productId: "${input.productId}",
                quantity: "${input.buyCount}",
              },
            ],
          },
        },
        bodySchema: [
          {
            name: "requestNo",
            label: "请求流水号",
            remark: "幂等键，防重复提交",
            type: "string",
            required: true,
            batchEnabled: false,
          },
          {
            name: "timestamp",
            label: "请求时间",
            remark: "下单时间戳",
            type: "string",
            required: true,
            batchEnabled: false,
          },
          {
            name: "buyer",
            label: "买家信息",
            remark: "购买者相关字段",
            type: "object",
            required: true,
            batchEnabled: false,
            children: [
              {
                name: "id",
                label: "买家ID",
                remark: "买家用户编号",
                type: "string",
                required: true,
                batchEnabled: false,
              },
            ],
          },
          {
            name: "items",
            label: "商品明细",
            remark: "下单商品列表",
            type: "array",
            required: true,
            batchEnabled: false,
            children: [
              {
                name: "productId",
                label: "商品编号",
                remark: "SKU编号",
                type: "string",
                required: true,
                batchEnabled: false,
              },
              {
                name: "quantity",
                label: "购买数量",
                remark: "购买件数",
                type: "number",
                required: true,
                batchEnabled: false,
              },
            ],
          },
        ],
        responseSchema: [
          {
            name: "success",
            label: "是否成功",
            remark: "业务处理结果标识",
            type: "boolean",
            required: false,
            batchEnabled: false,
            defaultValue: true,
          },
          {
            name: "errorCode",
            label: "错误码",
            remark: "失败时返回的错误编码",
            type: "string",
            required: false,
            batchEnabled: false,
          },
          {
            name: "errorMsg",
            label: "错误信息",
            remark: "失败时的错误描述",
            type: "string",
            required: false,
            batchEnabled: false,
          },
          {
            name: "data",
            label: "订单数据",
            remark: "成功时返回的订单详情",
            type: "object",
            required: false,
            batchEnabled: false,
            children: [
              {
                name: "orderNo",
                label: "全局订单号",
                remark: "订单唯一标识，格式TD+日期+序号",
                type: "string",
                required: false,
                batchEnabled: false,
                defaultValue: "TD20260604889901",
              },
              {
                name: "payAmount",
                label: "应付金额",
                remark: "订单实付金额(元)",
                type: "number",
                required: false,
                batchEnabled: false,
                defaultValue: 199.5,
              },
              {
                name: "orderStatus",
                label: "订单状态",
                remark: "PENDING=待付款, PAID=已付款",
                type: "string",
                required: false,
                batchEnabled: false,
                defaultValue: "PENDING",
              },
            ],
          },
        ],
        responseHandling: {
          expectedContentType: "JSON",
          statusCode: { success: [200] },
          businessSuccess: {
            allOf: [{ path: "${RES_BODY(success)}", op: "EQ", value: "true" }],
          },
          businessFailure: {
            anyOf: [
              { path: "${RES_BODY(errorCode)}", op: "EXISTS", value: "" },
            ],
          },
        },
        outputMapping: {
          orderNo: "${RES_BODY(data.orderNo)}",
          payAmount: "${RES_BODY(data.payAmount)}",
          orderStatus: "${RES_BODY(data.orderStatus)}",
        },
        outputMeta: {
          orderNo: {
            label: "全局订单号",
            remark: "订单唯一标识，用于后续查询和对账",
          },
          payAmount: { label: "应付金额", remark: "单位元，精确到分" },
          orderStatus: { label: "订单状态", remark: "PENDING=待付款" },
        },
        httpParamMapping: {},
      },
      {
        stepId: "record_order_log",
        stepName: "4. 记录订单日志",
        type: "SQL",
        enabled: true,
        dependsOn: ["create_order"],
        description: "将订单创建结果写入日志表，便于后续审计追溯",
        operation: "INSERT",
        sysCode: "trade",
        datasourceCode: "tradeDb",
        sqlText:
          "INSERT INTO order_audit_log (order_no, user_id, product_id, pay_amount, created_at) VALUES (:orderNo, :userId, :productId, :payAmount, CURRENT_TIMESTAMP)",
        normalizedSql:
          "INSERT INTO order_audit_log (order_no, user_id, product_id, pay_amount, created_at) VALUES (:orderNo, :userId, :productId, :payAmount, CURRENT_TIMESTAMP)",
        paramMapping: {
          orderNo: "${steps.create_order.outputs.orderNo}",
          userId: "${input.userId}",
          productId: "${input.productId}",
          payAmount: "${steps.create_order.outputs.payAmount}",
        },
        outputMapping: {
          insert_id: "insert_id",
        },
        outputMeta: {
          insert_id: {
            label: "日志主键",
            remark: "自增ID，用于确认日志写入成功",
          },
        },
      },
    ],
    resultSchema: [
      {
        name: "orderNo",
        label: "订单号",
        remark: "全局唯一订单号",
        type: "string",
        required: false,
        batchEnabled: false,
      },
      {
        name: "payAmount",
        label: "应付金额",
        remark: "订单实付金额(元)",
        type: "number",
        required: false,
        batchEnabled: false,
      },
      {
        name: "userId",
        label: "用户ID",
        remark: "下单用户标识",
        type: "string",
        required: false,
        batchEnabled: false,
      },
      {
        name: "productId",
        label: "商品编号",
        remark: "购买商品SKU",
        type: "string",
        required: false,
        batchEnabled: false,
      },
    ],
    resultMapping: {
      "$.orderNo": "${steps.create_order.outputs.orderNo}",
      "$.payAmount": "${steps.create_order.outputs.payAmount}",
      "$.userId": "${input.userId}",
      "$.productId": "${input.productId}",
    },
    errorPolicy: "STOP_ON_ERROR",
    batchConfig: {
      enabled: true,
      maxConcurrency: 5,
      failurePolicy: "CONTINUE_ON_ERROR",
    },
  };
}
